# To launch the cargo embed with the correct set of features "defmt" run the following:
# cargo embed default -- --no-default-features --features defmt
# or the Alias: cargo embed-d  

[default.general]
chip                = "RP2040"
log_level           = "INFO"
connect_under_reset = false    # RP2040 does not support connect_under_reset

[default.probe]
protocol = "Swd"
speed    = 20000
# If you only have one probe cargo embed will pick automatically
# Otherwise: add your probe's VID/PID/serial to filter

## rust-dap
# usb_vid = "6666"
# usb_pid = "4444"
# serial = "test"


[default.flashing]
enabled = true

[default.reset]
enabled         = true
halt_afterwards = false


[default.rtt]
enabled     = true
up_mode     = "NoBlockSkip"
timeout     = 3000
log_enabled = true
log_path    = "./logs"

[default.gdb]
enabled               = false
gdb_connection_string = "127.0.0.1:2345"
