[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Choose a default "cargo run" tool which flashes the firmware
# - elf2uf2-rs - loads firmware over USB when the rp2040 is in boot mode
# - probe-rs   - provides flashing and defmt via a hardware debugger, and stack unwind on panic
#                use --target-sel 0x01002927 instead of --chip if exp freezing issues

# Flashing via a hardware probe. Can run "cargo embed-d" instead. 
# runner = "probe-rs run --chip rp2040 --protocol swd" 

# Flashing to a USB mounted Pico
runner = "elf2uf2-rs -d"

linker = "flip-link"


[build]
target = "thumbv6m-none-eabi"


[env]
DEFMT_LOG = "trace"


[alias]
# base
b = "build"
r = "run"
s = "size"

# release
br = "build --release"
rr = "run --release"
sr = "size --release"


# default_dev
bd = "build --no-default-features --features default-dev"
rd = "run --no-default-features --features default-dev"
sd = "size --no-default-features --features default-dev"

brd = "br --no-default-features --features default-dev"
rrd = "rr --no-default-features --features default-dev"
srd = "sr --no-default-features --features default-dev"
