[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Choose a default "cargo run" tool which flashes the firmware
# - elf2uf2-rs - loads firmware over USB when the rp2040 is in boot mode
# - probe-rs   - provides flashing and defmt via a hardware debugger, and stack unwind on panic
#                use --target-sel 0x01002927 instead of --chip if exp freezing issues

# Flashing via a hardware probe. Can run "cargo embed-d" instead. 
# runner = "probe-rs run --chip rp2040 --protocol swd" 

# Flashing to a USB mounted Pico
runner = "elf2uf2-rs -d"

linker = "flip-link"


[build]
target = "thumbv6m-none-eabi"


[env]
DEFMT_LOG = "trace"


[alias]
build-d = 'build --no-default-features --features default-dev'
run-d   = 'run --no-default-features --features default-dev'
embed-d = 'embed --no-default-features --features default-dev'
size-d  = 'size --no-default-features --features default-dev'
